# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: lint-fix
        name: lint-fix
        entry: make lint-fix
        language: system
        stages: [pre-push]
        verbose: true
        pass_filenames: false
      - id: tests
        name: unit tests
        entry: go test -failfast ./...
        language: system
        stages: [pre-push]
        verbose: true
        pass_filenames: false
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.43.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ "@commitlint/config-conventional" ]
