name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          mkdir -p output
          export GOOS=darwin  && export GOARCH=amd64 && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=darwin  && export GOARCH=arm64 && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=386   && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=amd64 && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=arm   && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=linux   && export GOARCH=arm64 && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH
          export GOOS=windows && export GOARCH=386   && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH.exe
          export GOOS=windows && export GOARCH=amd64 && go build -ldflags="-s -w" -o ./output/snyk-lsp.$GOOS.$GOARCH.exe
          chmod +x output/*

      - name: Test
        env:
          DEEPROXY_API_URL: ${{secrets.DEEPROXY_API_URL}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN }}
        run: |
          echo "Downloading CLI..."
          curl https://static.snyk.io/cli/latest/snyk-linux > snyk
          chmod +x snyk
          export PATH=$PATH:$PWD
          go test -v ./...

      - name: Golang code analysis
        run: |
          go vet
          go fmt

      - name: Staticcheck code analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Snyk
        env:
          DEEPROXY_API_URL: ${{secrets.DEEPROXY_API_URL}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN }}
        run: |
          chmod +x snyk
          ./snyk test
          ./snyk code test

      - name: Compress binaries with UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: output/*
          args: "-9f"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        if: ${{ !env.ACT }}
        with:
          semantic_version: 16
          branches: |
            [ "main" ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ !env.ACT && env.GITHUB_REF_TYPE == 'tag' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "${{ github.sha }}"
          files: |
            output/*
